import 'package:flutter/material.dart';

class InfoPage extends StatefulWidget {
  const InfoPage({Key? key}) : super(key: key);

  @override
  State<InfoPage> createState() => _InfoPageState();
}

class _InfoPageState extends State<InfoPage> {
  bool showing_license = false;

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        children: [
          Text(
            """
Instructions:

Phase Control: Change the phase of each motor manually in degrees.

Cartesian Control: Change the position of the end effector by inputing cartesian coordinates in mm.

Learn Path: Turns off the motor and memorizes the robot's motions, saving them in a file. The name of the file defaults to learned_path and is saved in the user's home directory. Directory traversal in the file name is not permitted. This same file can be replayed from Load Path.

Load Path: Choose an instruction file to run. One may choose a file from Learn Path or compose one's own instruction file. The instruction file can contain the following commands:

cartesian x x x
phase x x x
replay x x x

where the x are integers, phase coordinates are written in degrees, cartesian coordinates are written in millimeters, replay coordinates are written in coordinates unique to the motor which should not be written by hand, only taken from files generated by Learn Path.

Here are examples:

phase 10 10 10
cartesian 50 50 -200       
            """
          ),
          ElevatedButton(
            onPressed: () {
              setState(() {
                showing_license = !showing_license;
              });
            },
            child: Text(showing_license ? 'hide license': 'show license for open_file package'),
            style: ElevatedButton.styleFrom(
                backgroundColor: showing_license ? Colors.red: Colors.blue,
                foregroundColor: Colors.white,
            ),
          ),
          if (showing_license)
            Text(
              """
The following applies to the flutter open_file package, used in Load Path to open files:

Copyright 2018 crazecoder. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above
      copyright notice, this list of conditions and the following
      disclaimer in the documentation and/or other materials provided
      with the distribution.
    * Neither the name of Google Inc. nor the names of its
      contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
              """
            )
        ],
      )
    );
  }
}